//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sho()
        {
            this.Order_Details = new HashSet<Order_Detail>();
        }
    
        public int ShoesID { get; set; }
        public string ShoesName { get; set; }
        public int SupplierID { get; set; }
        public int QuantityRemaining { get; set; }
        public decimal UnitPrice { get; set; }
        public Nullable<bool> Discontinued { get; set; }
        public byte[] Image { get; set; }
        public string ImagePath { get; set; }
        public int Size { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Detail> Order_Details { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
